# Generated by Django 3.1.6 on 2021-03-01 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_commits', models.IntegerField()),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RepoContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('sha', models.CharField(max_length=200)),
                ('repo_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='gitAPI.githubrepo')),
            ],
        ),
        migrations.CreateModel(
            name='RepoCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('committed_at', models.DateTimeField()),
                ('repo_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='gitAPI.githubrepo')),
            ],
        ),
        migrations.CreateModel(
            name='RepoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('repo_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gitAPI.githubrepo')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_repos_update', models.DateTimeField(blank=True, null=True)),
                ('gitinuser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitAPI.githubuser'),
        ),
    ]
