# Generated by Django 3.1.6 on 2021-03-10 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repocomment',
            name='repo_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_comments', to='gitAPI.githubrepo'),
        ),
    ]
