# Generated by Django 3.1.6 on 2021-02-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='homepage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
