# Generated by Django 3.1.6 on 2021-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0002_auto_20210310_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepoComment',
        ),
    ]
