# Generated by Django 3.1.6 on 2021-02-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0002_auto_20210219_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=300)),
                ('sha', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('repo_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='gitAPI.githubrepo')),
            ],
        ),
    ]
