# Generated by Django 3.1.6 on 2021-02-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0002_auto_20210217_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
