# Generated by Django 3.1.6 on 2021-03-13 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0003_delete_repocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='refreshed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
