# Generated by Django 3.1.6 on 2021-02-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gitAPI', '0004_auto_20210217_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='gitinuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gitinuser'),
        ),
        migrations.DeleteModel(
            name='GitinUser',
        ),
    ]
