# Generated by Django 3.1.6 on 2021-02-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gitinuser_profile_img'),
        ('gitAPI', '0005_auto_20210217_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.gitinuser')),
                ('repo_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gitAPI.githubrepo')),
            ],
        ),
    ]
