# Generated by Django 3.1.6 on 2021-02-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0005_remove_githubrepo_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='number_of_commits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
