# Generated by Django 3.1.6 on 2021-02-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0006_auto_20210220_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='path',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
