# Generated by Django 3.1.6 on 2021-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0006_repocomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='repocomments',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
