# Generated by Django 3.1.6 on 2021-02-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gitinuser_profile_img'),
        ('gitAPI', '0007_repocomments_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepoComments',
            new_name='RepoComment',
        ),
    ]
