# Generated by Django 3.1.6 on 2021-02-21 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0007_githubrepo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='repocommit',
            name='committed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
