# Generated by Django 3.1.6 on 2021-02-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0009_auto_20210218_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('commit', models.JSONField()),
                ('url', models.CharField(max_length=300)),
                ('repo_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='gitAPI.githubrepo')),
            ],
        ),
    ]
