# Generated by Django 3.1.6 on 2021-02-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0009_repocommit_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repocommit',
            name='commit',
        ),
    ]
