# Generated by Django 3.1.6 on 2021-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0010_repocommit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repocommit',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
