# Generated by Django 3.1.6 on 2021-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0010_remove_repocommit_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='repocontentfile',
            name='name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
