# Generated by Django 3.1.6 on 2021-02-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0011_repocontentfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repocontentfile',
            name='sha',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
