# Generated by Django 3.1.6 on 2021-02-23 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitAPI', '0012_repocontentfile_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='gitinuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
