# Generated by Django 3.1.6 on 2021-02-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitAPI', '0014_githubuser_last_repos_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='last_repos_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
