# Generated by Django 3.1.6 on 2021-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitinuser',
            old_name='username',
            new_name='profilename',
        ),
    ]
