# Generated by Django 3.1.7 on 2021-05-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(default='how to use github API with django', max_length=100),
            preserve_default=False,
        ),
    ]
