# Generated by Django 3.1.7 on 2021-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorial_thumbnail/'),
        ),
    ]
